### ISSUE TITLE
也许是环境变量的问题

### ISSUE THREAD

**Issue by whhxp** [Sorosliu1029/Rule-based_Expert_System#1]
作者你好，我下载了你的代码，在windows7下尝试了一下。
我使用的的python2.7.13，在win下安装了pip，然后
```
pip install opencv-python
``` 
main_frame的121行会有个

>   File ".\main_frame.py", line 121, in open_picture
>     self.SetTitle(self.title + ' -- Shape from: ' + re.findall(r'test/(.*)$', self.pic_path)[0])
> IndexError: list index out of range

这样的错误，我删掉正则直接输出目录就没问题了。
然后发现opencv这边好像会出错，
```
Traceback (most recent call last):
  File ".\main_frame.py", line 129, in open_picture
    self.engine = setup_engine(self.pic_path)
  File "..\engine\inference_engine.py", line 142, in setup_engine
    handler = Handler(image_source)
  File "..\Picture_handler\cv_handler2.py", line 73, in __init__
    self.contours = get_contours(self.src)[1:]  # contours are in clock-wise order
  File "..\Picture_handler\cv_handler2.py", line 51, in get_contours
    contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack
```

可能是版本出错了，opencv3以上返回的是3个变量，不是2个

**Comment by whhxp** [comment]
哦问题解决了，作者你可能安装时opencv2版本，我用的是3，所以会有一些问题。
..\Picture_handler\cv_handler2.py 51行
改成
```
img, contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
```

另外，GUI\main_frame.py里面第29行
改成
```
                cv2.line(image, line.point1, line.point2, (0, 255, 0), 2, cv2.LINE_AA)
```

**Comment by Sorosliu1029** [comment]
好的，谢谢提出这个问题。
这个项目有点久了，其中的细节我也不是很清楚了。
😃
